cp arch/arm/mach-msm/dal_remotetest.ko modules/
cp crypto/ansi_cprng.ko modules/
cp block/test-iosched.ko modules/
cp drivers/scsi/scsi_wait_scan.ko modules/
cp drivers/mtd/tests/mtd_oobtest.ko modules/
cp drivers/mtd/tests/mtd_pagetest.ko modules/
cp drivers/mtd/tests/mtd_readtest.ko modules/
cp drivers/mtd/tests/mtd_speedtest.ko modules/
cp drivers/mtd/tests/mtd_stresstest.ko modules/
cp drivers/mtd/tests/mtd_subpagetest.ko modules/
cp drivers/mtd/tests/mtd_torturetest.ko modules/
cp drivers/mtd/tests/mtd_nandecctest.ko modules/
cp drivers/mtd/tests/mtd_erasepart.ko modules/
cp drivers/net/wireless/ray_cs.ko modules/
cp drivers/net/wireless/ath/ath6kl/ath6kl_sdio.ko modules/
cp drivers/net/wireless/ath/ath.ko modules/
cp drivers/net/wireless/libra/librasdioif.ko modules/
cp drivers/input/evbug.ko modules/
cp drivers/media/video/gspca/gspca_main.ko modules/
cp drivers/pcmcia/pcmcia_core.ko modules/
cp drivers/pcmcia/pcmcia.ko modules/
cp drivers/pcmcia/pcmcia_rsrc.ko modules/
cp net/wireless_ath/cfg80211.ko modules/
